apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  # Password: hungns2025
  mysql-root-password: aHVuZ25zMjAyNQ==
  mysql-password: aHVuZ25zMjAyNQ==
